### ISSUE TITLE
Do you have a way of dynamically creating tiny editors in js?

### ISSUE THREAD

**Issue by syonfox** [fvilers/tiny-editor#21]
This should at least be documented

**Comment by fvilers** [comment]
Sorry for the late reply. To create a new editor, you declare a <div> with the data attribute `data-tiny-editor`. There's currently no exposed method to initialize an editor from javascript. Do you need to feature ?

**Comment by fvilers** [comment]
Version 0.3.0 expose a global method (`window.__tinyEditor.transformToEditor()`) to transform any element (usually a <div>) to an editor.

**Comment by syonfox** [comment]
that works I can migrate to the npm version later.. I also ended up adding Caret util to my project to support getting and setting the carrot position from tiny editors Could this be worth including in the core. Ill make another issue
