### ISSUE TITLE
Auto-focus, option to disable?

### ISSUE THREAD

**Issue by gbrits** [fvilers/tiny-editor#49]
Hi there, great lightweight solution, just noticed in my use-case it forces focusing on the element, which in my case is at the bottom of the page, so it's forcing the user to scroll to the bottom. There doesn't appear to be an option to disable autofocus?

**Comment by fvilers** [comment]
An option has been added with version 0.5.0 that has just been published. Use `data-autofocus="no"` to remove autofocus from the editor.

**Comment by gbrits** [comment]
Perfect. Thanks. Amazing speed ;)
